version: '3'

services:
  web:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://flask@postgres/flask
  
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: flask
      POSTGRES_DB: flask
